name: CI Build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

jobs:
  build-run-and-test:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
      
      - name: Copy unit test results
        run: docker cp $(docker-compose ps -q todolistapi):/app/testresults ./test-results
      
      - name: List unit test results
        run: ls ./test-results
      
      - name: Unit Tests Reporter
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Unit Tests
          path: "**/TodoListUnitTests.trx"                            
          reporter: dotnet-trx
          only-summary: 'false'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: true          
      
      - name: Run Newman (API Tests)        
        uses: docker://postman/newman:latest
        with:
          args: run --network host TodoListApiTests/postman/TodoListApi.postman_collection.json --env-var "baseUrl=http://localhost:8080" --verbose --insecure --reporters cli,junit --reporter-junit-export api-tests-results.xml

      - name: API Tests Reporter
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: API Tests
          path: api-tests-results.xml
          reporter: java-junit
          fail-on-error: true
      
      - name: Stop Docker Compose
        run: docker-compose down
        
        
