name: CI Build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

jobs:
  build-run-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
      
      - name: Copy unit test results
        run: docker cp $(docker-compose ps -q todolistapi):/app/testresults ./test-results
      
      - name: List unit test results
        run: ls ./test-results
      
      - name: Publish unit test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results
          path: ./test-results
          
      - name: Stop Docker Compose
        run: docker-compose down
        
        
