name: CI Build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

jobs:
  build-run-and-test:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
      
      - name: Copy unit test results
        run: docker cp $(docker-compose ps -q todolistapi):/app/testresults ./test-results
      
      - name: List unit test results
        run: ls ./test-results
      
      - name: Test Reporter
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Unit Tests
          path: "**/TodoListUnitTests.trx"                            
          reporter: dotnet-trx
          only-summary: 'false'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: true          
      
      - name: Stop Docker Compose
        run: docker-compose down
        
        
